#ifndef __ORIGIN_BEHAVIOR_TREE_DEBUG_H_
#define __ORIGIN_BEHAVIOR_TREE_DEBUG_H_

#include "oConfig.h"

#if (ORIGIN_TARGET_MODE == ORIGIN_MODE_DEBUG)
#define ORIGIN_BEHAVIOR_TREE_DEBUG
#endif//(ORIGIN_TARGET_MODE == ORIGIN_MODE_DEBUG)

#endif//__ORIGIN_BEHAVIOR_TREE_DEBUG_H_