#ifndef __ORIGIN_STATE_DEBUG_H_
#define __ORIGIN_STATE_DEBUG_H_

#include "oConfig.h"

#if (ORIGIN_TARGET_MODE == ORIGIN_MODE_DEBUG)
#define ORIGIN_STATE_DEBUG
#endif // (ORIGIN_TARGET_MODE == ORIGIN_MODE_DEBUG)

#ifdef ORIGIN_STATE_DEBUG
//ORIGIN_STATE_TARGET
#define ORIGIN_STATE_TARGET_MODE		ORIGIN_MODE_DEBUG

#else
//ORIGIN_STATE_TARGET
#define ORIGIN_STATE_TARGET_MODE		ORIGIN_MODE_RELEASE

#endif // ORIGIN_STATE_DEBUG


#endif/**__ORIGIN_STATE_DEBUG_H_**/